C4Component
  title "Componentes: SWB-LOG-OPT"
  Container_Boundary("domain", "Domain") {
    Component("fd8465", "missing-proof-of-delivery.exception", "TypeScript", "")
    Component("ffea38", "missing-reason-code.exception", "TypeScript", "")
    Component("ff0592", "geofence-violation.exception", "TypeScript", "")
    Component("f2134f", "event-publisher", "TypeScript", "")
    Component("ff6b6f", "package-status-changed.event", "TypeScript", "")
    Component("f1584d", "no-hay-vehiculos-disponibles.exception", "TypeScript", "")
    Component("f139ca", "formato-archivo-invalido.exception", "TypeScript", "")
    Component("fd75ed", "paquete-con-coordenadas-invalidas.exception", "TypeScript", "")
    Component("fd7467", "file-parser.service", "TypeScript", "")
    Component("fb7814", "time-window.vo", "TypeScript", "")
    Component("f6a276", "location.vo", "TypeScript", "")
    Component("fefe61", "no-feasible-route.exception", "TypeScript", "")
    Component("f5183b", "route-optimization.service", "TypeScript", "")
    Component("f2d17e", "vehicle.repository", "TypeScript", "")
    Component("fba747", "package.repository", "TypeScript", "")
    Component("fa7fe5", "stop.entity", "TypeScript", "")
    Component("faf79a", "package.entity", "TypeScript", "")
    Component("f7aa69", "vehicle.entity", "TypeScript", "")
    Component("f73b28", "route.entity", "TypeScript", "")
  }
  Container_Boundary("application", "Application") {
    Component("fd517c", "marcar-estado-entrega-paquete.output", "TypeScript", "")
    Component("fae4a9", "marcar-estado-entrega-paquete.input", "TypeScript", "")
    Component("f0537c", "marcar-estado-entrega-paquete.use-case-impl", "TypeScript", "")
    Component("f99a9a", "marcar-estado-entrega-paquete.use-case", "TypeScript", "")
    Component("f47fa5", "cargar-paquetes-masivamente.output", "TypeScript", "")
    Component("fbd6f4", "cargar-paquetes-masivamente.input", "TypeScript", "")
    Component("f122ca", "cargar-paquetes-masivamente.use-case", "TypeScript", "")
    Component("f31ed4", "cargar-paquetes-masivamente.use-case-impl", "TypeScript", "")
    Component("fc75dd", "calcular-ruta-optima.input", "TypeScript", "")
    Component("fbd777", "calcular-ruta-optima.output", "TypeScript", "")
    Component("fa29aa", "calcular-ruta-optima.use-case", "TypeScript", "")
    Component("f87e98", "calcular-ruta-optima.use-case-impl", "TypeScript", "")
    Component("f34b2f", "marcar-estado-entrega-paquete.use-case.spec", "TypeScript", "")
    Component("f8bcbf", "marcar-estado-entrega-paquete.use-case-impl.spec", "TypeScript", "")
  }
  Container_Boundary("infrastructure", "Infrastructure") {
    Component("fbf1cb", "event-publisher.service", "TypeScript", "")
    Component("f908f0", "entrega-paquetes.controller", "TypeScript", "")
    Component("f9a7de", "txt-file-parser.service", "TypeScript", "")
    Component("ff2282", "carga-masiva.controller", "TypeScript", "")
    Component("f2f868", "google-maps-route-optimization.service", "TypeScript", "")
    Component("f173aa", "in-memory-ruta.repository", "TypeScript", "")
    Component("fb49b9", "in-memory-package.repository", "TypeScript", "")
    Component("ff00e8", "in-memory-vehicle.repository", "TypeScript", "")
    Component("f8e073", "rutas.controller", "TypeScript", "")
  }
  Container_Boundary("other", "Other") {
    Component("f33390", "main", "TypeScript", "")
    Component("f8bb3d", "app.module", "TypeScript", "")
    Component("f3b72e", "entrega-paquetes.module", "TypeScript", "")
    Component("f84951", "carga-masiva.module", "TypeScript", "")
    Component("fe1d1b", "rutas.module", "TypeScript", "")
    Component("f65d05", "UseCase", "TypeScript", "")
    Component("f3d9df", "UniqueEntityID", "TypeScript", "")
    Component("fa873f", "DomainEvent", "TypeScript", "")
    Component("fc7002", "ValueObject", "TypeScript", "")
    Component("ffa298", "AggregateRoot", "TypeScript", "")
    Component("f6d80c", "Entity", "TypeScript", "")
    Component("f008a2", "DomainException", "TypeScript", "")
    Component("fdad47", "EliminarParadaDeRutaUseCase", "TypeScript", "")
    Component("fb885f", "CancelarRutaUseCase", "TypeScript", "")
    Component("f3b73f", "AgregarParadaARutaUseCase", "TypeScript", "")
    Component("f178a4", "CambiarEstadoVehiculoUseCase", "TypeScript", "")
    Component("fedf80", "CompletarRutaUseCase", "TypeScript", "")
    Component("fa5b04", "AsignarVehiculoARutaUseCaseImpl", "TypeScript", "")
    Component("f392d4", "CrearRutaOptimaUseCaseImpl", "TypeScript", "")
    Component("fb4cfe", "AsignarPaqueteARutaUseCase", "TypeScript", "")
    Component("fb9f9a", "ActualizarUbicacionVehiculoUseCase", "TypeScript", "")
    Component("fde6fa", "RecalcularRutaUseCase", "TypeScript", "")
    Component("f8a24a", "MarcarPaqueteEnTransitoUseCase", "TypeScript", "")
    Component("f0db41", "ObtenerDetallesRutaUseCase", "TypeScript", "")
    Component("f2d58b", "AsignarVehiculoARutaUseCase", "TypeScript", "")
    Component("fb0023", "CancelarAsignacionPaqueteUseCase", "TypeScript", "")
    Component("f61556", "CrearRutaOptimaUseCase", "TypeScript", "")
    Component("f95848", "ActivarRutaUseCase", "TypeScript", "")
    Component("fdaf61", "MarcarPaqueteEntregadoUseCase", "TypeScript", "")
    Component("ff395e", "ObtenerDetallesRutaUseCaseImpl", "TypeScript", "")
    Component("f20c34", "AsignarVehiculoARuta.input", "TypeScript", "")
    Component("fc2c2f", "ObtenerDetallesRuta.output", "TypeScript", "")
    Component("f65480", "AsignarVehiculoARuta.output", "TypeScript", "")
    Component("f06c38", "ObtenerDetallesRuta.input", "TypeScript", "")
    Component("f11b93", "RepositorioRutas", "TypeScript", "")
    Component("f1ceab", "RepositorioPaquetes", "TypeScript", "")
    Component("fbbb47", "ServicioGeocodificacion", "TypeScript", "")
    Component("fcbd4a", "ServicioOptimizacionRutas", "TypeScript", "")
    Component("fd046a", "RepositorioVehiculos", "TypeScript", "")
    Component("fe5e8e", "ServicioInformacionTrafico", "TypeScript", "")
    Component("fa5551", "Vehiculo", "TypeScript", "")
    Component("f12e20", "Paquete", "TypeScript", "")
    Component("fa486a", "EstadoVehiculo", "TypeScript", "")
    Component("f29528", "EstadoPaquete", "TypeScript", "")
    Component("fb91a8", "EstadoRuta", "TypeScript", "")
    Component("f05b3c", "Ruta", "TypeScript", "")
    Component("f5f79e", "PaqueteYaAsignadoException", "TypeScript", "")
    Component("fc2201", "EstadoInvalidoPaqueteException", "TypeScript", "")
    Component("f4e2b8", "UnreachableDestinationException", "TypeScript", "")
    Component("f926b2", "NoHayRutaFactibleException", "TypeScript", "")
    Component("f83263", "VentanaEntregaInvalidaException", "TypeScript", "")
    Component("f2bce0", "CapacidadVehiculoExcedidaException", "TypeScript", "")
    Component("f1b355", "EstadoInvalidoRutaException", "TypeScript", "")
    Component("f175db", "PaqueteNoEncontradoException", "TypeScript", "")
    Component("f8a96f", "ViolacionRestriccionRutaException", "TypeScript", "")
    Component("f106af", "RutaYaTieneVehiculoException", "TypeScript", "")
    Component("f47ae5", "VehiculoNoEncontradoException", "TypeScript", "")
    Component("f0d544", "EstadoInvalidoVehiculoException", "TypeScript", "")
    Component("f3d77e", "RutaNoEncontradaException", "TypeScript", "")
    Component("fcd761", "CondicionTrafico", "TypeScript", "")
    Component("f3d6a4", "VentanaTiempo", "TypeScript", "")
    Component("fd26fc", "VehiculoId", "TypeScript", "")
    Component("f33adf", "RutaId", "TypeScript", "")
    Component("fba872", "Ubicacion", "TypeScript", "")
    Component("fc52f7", "Parada", "TypeScript", "")
    Component("f54660", "Distancia", "TypeScript", "")
    Component("f1af21", "Duracion", "TypeScript", "")
    Component("f01a4b", "PaqueteId", "TypeScript", "")
    Component("f5954f", "SegmentoRuta", "TypeScript", "")
    Component("f8c31a", "CrearRutaOptimaUseCaseImpl.spec", "TypeScript", "")
  }