C4Component
  title "Componentes: SWB-LOG-OPT"
  Container_Boundary("other", "Other") {
    Component("fc4fd5", "main", "TypeScript", "")
    Component("f076f5", "app.module", "TypeScript", "")
    Component("f34af8", "UniqueEntityID", "TypeScript", "")
    Component("fb3115", "DomainEvent", "TypeScript", "")
    Component("f4314a", "ValueObject", "TypeScript", "")
    Component("f03c2a", "AggregateRoot", "TypeScript", "")
    Component("f9777a", "Entity", "TypeScript", "")
    Component("f3400d", "DomainException", "TypeScript", "")
    Component("f465f5", "EliminarParadaDeRutaUseCase", "TypeScript", "")
    Component("fbe205", "CancelarRutaUseCase", "TypeScript", "")
    Component("fa886f", "AgregarParadaARutaUseCase", "TypeScript", "")
    Component("ffd5bb", "CambiarEstadoVehiculoUseCase", "TypeScript", "")
    Component("fc8b56", "CompletarRutaUseCase", "TypeScript", "")
    Component("f7bc44", "CrearRutaOptimaUseCaseImpl", "TypeScript", "")
    Component("fb1b3c", "AsignarPaqueteARutaUseCase", "TypeScript", "")
    Component("f6a832", "ActualizarUbicacionVehiculoUseCase", "TypeScript", "")
    Component("f6e0b1", "RecalcularRutaUseCase", "TypeScript", "")
    Component("ff07a1", "MarcarPaqueteEnTransitoUseCase", "TypeScript", "")
    Component("f6a7d4", "CancelarAsignacionPaqueteUseCase", "TypeScript", "")
    Component("f4cf4b", "CrearRutaOptimaUseCase", "TypeScript", "")
    Component("fb8406", "ActivarRutaUseCase", "TypeScript", "")
    Component("f97e13", "MarcarPaqueteEntregadoUseCase", "TypeScript", "")
    Component("fdf9f5", "RepositorioRutas", "TypeScript", "")
    Component("fbde52", "RepositorioPaquetes", "TypeScript", "")
    Component("fc9149", "ServicioGeocodificacion", "TypeScript", "")
    Component("f44055", "ServicioOptimizacionRutas", "TypeScript", "")
    Component("f6dcc4", "RepositorioVehiculos", "TypeScript", "")
    Component("f8cbde", "ServicioInformacionTrafico", "TypeScript", "")
    Component("f618bb", "Vehiculo", "TypeScript", "")
    Component("fc039b", "Paquete", "TypeScript", "")
    Component("f6afaa", "EstadoVehiculo", "TypeScript", "")
    Component("fc4a04", "EstadoPaquete", "TypeScript", "")
    Component("f1bb50", "EstadoRuta", "TypeScript", "")
    Component("f967ff", "Ruta", "TypeScript", "")
    Component("f11423", "PaqueteYaAsignadoException", "TypeScript", "")
    Component("f63683", "EstadoInvalidoPaqueteException", "TypeScript", "")
    Component("f85bca", "UnreachableDestinationException", "TypeScript", "")
    Component("f14a1d", "NoHayRutaFactibleException", "TypeScript", "")
    Component("f89859", "VentanaEntregaInvalidaException", "TypeScript", "")
    Component("f671de", "CapacidadVehiculoExcedidaException", "TypeScript", "")
    Component("fe7e97", "EstadoInvalidoRutaException", "TypeScript", "")
    Component("f8da9b", "PaqueteNoEncontradoException", "TypeScript", "")
    Component("f5d63b", "ViolacionRestriccionRutaException", "TypeScript", "")
    Component("f0a4e5", "VehiculoNoEncontradoException", "TypeScript", "")
    Component("f058f3", "EstadoInvalidoVehiculoException", "TypeScript", "")
    Component("f970ee", "RutaNoEncontradaException", "TypeScript", "")
    Component("feeb5e", "CondicionTrafico", "TypeScript", "")
    Component("f3540c", "VentanaTiempo", "TypeScript", "")
    Component("fe82c5", "VehiculoId", "TypeScript", "")
    Component("f5d793", "RutaId", "TypeScript", "")
    Component("f6be9d", "Ubicacion", "TypeScript", "")
    Component("fbf9db", "Parada", "TypeScript", "")
    Component("f2ee81", "Distancia", "TypeScript", "")
    Component("fe9fb7", "Duracion", "TypeScript", "")
    Component("f09d80", "PaqueteId", "TypeScript", "")
    Component("fa1e61", "SegmentoRuta", "TypeScript", "")
    Component("f71a16", "CrearRutaOptimaUseCaseImpl.spec", "TypeScript", "")
  }